# Generated by Django 2.0.2 on 2023-05-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insumos_name', models.CharField(blank=True, max_length=100, null=True)),
                ('insumos_price', models.IntegerField(blank=True, null=True)),
                ('insumos_image', models.CharField(blank=True, max_length=240, null=True)),
                ('insumos_state', models.CharField(blank=True, default='No', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['insumos_name'],
            },
        ),
    ]
