# Generated by Django 2.0.2 on 2023-05-17 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_insumos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insumos',
            options={'ordering': ['insumos_name'], 'verbose_name': 'Insumo', 'verbose_name_plural': 'Insumos'},
        ),
        migrations.AddField(
            model_name='insumos',
            name='insumos_category',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.Category'),
        ),
    ]
