# Generated by Django 2.0.2 on 2023-05-17 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20230517_0603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_category',
        ),
        migrations.AddField(
            model_name='product',
            name='insumos_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventario.Category'),
        ),
    ]
