# Generated by Django 2.0.2 on 2023-05-17 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auto_20230517_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumos',
            name='insumos_category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.Category'),
        ),
    ]
