# Generated by Django 2.0.2 on 2023-05-17 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_auto_20230517_0706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='insumos',
            name='insumos_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventario.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventario.Category'),
        ),
        migrations.DeleteModel(
            name='Categorys',
        ),
    ]
