# Generated by Django 2.0.2 on 2023-06-02 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_auto_20230517_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumos',
            name='insumos_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.Category'),
        ),
    ]
