# Generated by Django 2.0.2 on 2023-06-07 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_auto_20230602_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insumos',
            old_name='insumos_category',
            new_name='insumos_categorys',
        ),
    ]
