# Generated by Django 2.0.2 on 2023-06-07 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_auto_20230606_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumos',
            name='insumos_categorys',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.Category'),
        ),
    ]
