# Generated by Django 2.0.2 on 2023-06-27 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_auto_20230627_0004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
