# Generated by Django 2.0.2 on 2023-06-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idVenta', models.IntegerField(blank=True, null=True, verbose_name='ID de la Venta')),
                ('motivoDev', models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo de la Devolucion')),
                ('direccionDev', models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion del Cliente')),
                ('correoDev', models.CharField(blank=True, max_length=100, null=True, verbose_name='Correo del Cliente')),
                ('fechaDev', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la Devolucion')),
            ],
            options={
                'verbose_name': 'Devolucion',
                'verbose_name_plural': 'Devoluciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Venta2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del producto')),
                ('precioProducto', models.IntegerField(blank=True, null=True, verbose_name='Precio del Producto')),
                ('cantidadProductos', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de Productos')),
                ('montoTotal', models.IntegerField(blank=True, null=True, verbose_name='Monto Total')),
                ('estado', models.CharField(blank=True, default='En curso', max_length=100, null=True, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('bloqDes', models.CharField(blank=True, default='Activo', max_length=100, null=True, verbose_name='Activo/Inactivo')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['id'],
            },
        ),
    ]
